### ISSUE TITLE
Cannot read obesity.bed file

### ISSUE THREAD

**Issue by lorenzoFabbri** [isglobal-brge/brgedata#3]
I am using `brgedata` version 1.10.0 with `R` version 4.0.2 on Ubuntu 18.04.
I am trying to use `read.plink` with the `obesity` files (which are not available in the directory of the package, so I downloaded them manually from the GitHub repository). The problem is that when I try to read `obesity.bed` I receive the following error message:

> Error in scan(..., :
>    line 1 did not have 3 elements

Any suggestion? Thank you. @isglobal-brge

**Comment by lorenzoFabbri** [comment]
Never mind. Apparently the `bed` file I downloaded from the repository was corrupted. I downloaded it again and now it works just fine.

**Comment by isglobal-brge** [comment]
Thank you Lorenzo, I am sorry for not having answering your question but I was on holidays without internet access
